### ISSUE TITLE
Event作る

### ISSUE THREAD

**Issue by techno-tanoC** [shinosakarb/tebukuro#10]
- [x] Event modelを作る
- [x] Event controllerを作る
- [x] Event specを作る

**Comment by techno-tanoC** [comment]
Event model作ります

**Comment by yukihirop** [comment]
events_controller.rb作ります。
event_selializer.rbも作ります。

**Comment by techno-tanoC** [comment]
communityへの関連付けします

**Comment by murajun1978** [comment]
merged all PRs
