### ISSUE TITLE
new contact

### ISSUE THREAD

**Issue by ogom** [shinosakarb/tebukuro#103]
### Problems and suggestions
User be able to contact the community.

### Countermeasure
Add contact schema.

* user_id
* community_id
* content

**Comment by gazayas** [comment]
Something like this?
```
$ rails g model Contact content:text user:references community:references
```

**Comment by murajun1978** [comment]
That's OK 👍 

If user is not signed in then need to enter an email address ? 🤔

### Signed in
* content

### Not sign in
* email
* content

**Comment by springaki** [comment]
tebukuro reboot の為、一旦 close します。
