### ISSUE TITLE
プロジェクトへの参加について

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#110]
### Question contents:質問内容
ytoriiと申します。先日のshinosaka.rbにて@murajun1978さんにこのプロジェクトを紹介して頂き参加を希望しているのですが、参加方法があればご教示下さい。

### Problems and suggestions:問題・課題点/提案
趣味でプログラミングをしておりOSSプロジェクトへの参加経験も無いため、スキルには自信がありません。足を引っ張らないように頑張りたいと思います。。

### Countermeasure:対応方法（案）
課題などへのアサインをして頂ければ幸いです。コーディング以外にもドキュメンテーションにも興味があります。

**Comment by chimame** [comment]
@ytorii さん、参加表明ありがとうございます。
そんなにかしこまらなくても気軽にご参加下さい 😄 

本プロジェクトはイベント管理システムを作っています。（ @murajun1978 に聞いていますか？）
本プロジェクトの方向性や開発手法は一部wikiにありますので一度読んでみて下さい。
バックエンドは「Ruby on Rails」で、フロントエンドには「React」を使用しております。

まだまだ初期段階なのですが、モデル構成およびルーティングは[このissue](https://github.com/shinosakarb/tebukuro/issues/33)で大体掴めるかと思います。
現状やらないといけないこと等はissueにあがっております。お手伝い頂けるのであれば見て頂いてissueでのやりとりやpull requestを頂ければと思います。

OSSの参加経験がないとのことですが、それならば一層ここで一度経験するのも良いかと思います。
もしissue等でのpublicでお聞きしにくいのであればshinosaka.rbのslackに「tebukuro」チャンネルがありますのでそちらで聞いて頂いても結構です。

>コーディング以外にもドキュメンテーションにも興味があります

すごく嬉しいですね。まずはREADMEをなんとかしないといけないので…
無理のない範囲でお互いのスキルを磨いていきましょう！

**Comment by ytorii** [comment]
早速のお返事ありがとうございます！
まずはモデル構成やルーティングを理解するようにします。
ドキュメンテーションは携わる機会が少ないので、挑戦してみたいと思っています。
まだまだ知識が不足しているので、調べたり質問したりすることが多いと思いますが、よろしくお願いします！
