### ISSUE TITLE
READMEの作成について

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#111]
### Problems and suggestions:問題・課題点/提案
tebukuroプロジェクトの内容理解を兼ねて、READMEの作成に着手したいと考えてます。
（これまでREADMEを作成した経験はないので勉強しながらになりますが。。）
作成にあたって、下記３点を相談させて頂きたいです。

- [x] 日本語か英語のどちらで作成するか
- [x]  プロジェクト内で適用する予定のLicence
- [x]  READMEに含めたいtebukuroのFeatures

### Countermeasure:対応方法（案）

- まずは目次と簡単な文章だけ作ってpull requestしようと思っています。
[わかりやすいREADME.mdを書く](http://deeeet.com/writing/2014/07/31/readme/)や、[わかりやすい README 駆動開発](http://qiita.com/b4b4r07/items/c80d53db9a0fd59086ec)といった記事を参考にしようと思っていますが、おススメの記事があればご教示下さい。
- wikiなどを読んだ所では、下記のFeaturesがあるかなと思いました。

  - Privateなイベントも作成できる
  - OSSなので（今のところ）無料
 
相談事項が多くて申し訳ないですが、宜しくお願いします。

**Comment by murajun1978** [comment]
Thanks 👍 

> 日本語か英語のどちらで作成するか

両方あったほうがいいと思いますが、とりあえずは日本語だけでもOKかなと

> プロジェクト内で適用する予定のLicence

BSD Licence にしようと思ってます

> READMEに含めたいtebukuroのFeatures

チェックボックスをつけて、リリースされたらチェックつけていくみたいな感じはどうでしょう？

**Comment by ogom** [comment]
READMEの作成は参考にしようとしているサイトでよいと思います。
すべてを `README` に記述せずに、別ファイルのリンクを利用するなどで、 文書の量を分散したほうがよいかもしれません。

**Comment by gazayas** [comment]
Welcome @ytorii !
> 日本語か英語のどちらで作成するか

When we make the English part, feel free to ask me any questions!
よろしくお願いします :octocat:

**Comment by chimame** [comment]
What is tebukuro?とかは最低限書くとは思いますが、付けておいてほしいですね。
英語は @gazayas が言うように手伝ってくれますよ 😄

**Comment by ytorii** [comment]
皆さん早速のコメントありがとうございます、ではいったん日本語で作成してみます！
（英語版を作るときは@gazayasさんヘルプ宜しくです！）

tebukuroの簡単な説明などはREADMEに書いて、セットアップ方法やBSDライセンスなどはリンクにして分散しようと思います。
Featuresは実装予定の機能や特徴をチェックボックスで並べようと思います。

**Comment by ytorii** [comment]
日本語版READMEの第１版を作成したので、このIsuueは一旦closeさせて頂きます。
