### ISSUE TITLE
Dealing with English and Japanese READMEs

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#113]
### Question contents:質問内容
Which is the best way to deal with English and Japanese README?

### Problems and suggestions:問題・課題点/提案
- English should be displayed first? Or Japanese first?
- English and Japanese READMEs should be separated to different files? Or coexisted in a same file?

### Countermeasure:対応方法（案）
I'm supposing 3 plans as below:

1. Japanese README, with link to English README_EN
2. English README, with link to Japanese README_JP
3. English and Japanese are mixed into one README

Same issue was discussed in [the other project](https://github.com/chocoby/jp_prefecture/issues/21).

**Comment by gazayas** [comment]
Good question.

I'm curious as well.

**Comment by ytorii** [comment]
Thank you for comment! Which plan is better do you think? (Or any other idea?)

I guess, for the time being most developers would join this project via japanese ruby communities, so plan 1 is better.
Of course, we can change the format int the later.

**Comment by ytorii** [comment]
Based on plan 1, created English README_EN.md apart from Japanese README.md.
