### ISSUE TITLE
Google Cloud Platformへのauto deploy 📦

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#115]
### Problems and suggestions:問題・課題点/提案
masterマージ時にAuto Deployできる環境を構築する

### Countermeasure:対応方法（案）
Google Cloud Platform へ Dockerを利用してAuto Deployする  :whale:

**Comment by murajun1978** [comment]
### TODO

#### first step
- [ ] CIのテストに成功したらDockerのイメージをビルド
- [ ] ビルドに成功すればGoogle Container Registryへpushする

#### second step
- [ ] Kubernetesのコンテナマニフェストを作成
- [ ] GCEへDeployする

#### third step
- [ ] CIでRegistryへのpushが成功したらGCEへDeployする

**Comment by springaki** [comment]
これも Issue分割して 一旦 closeしとくか
