### ISSUE TITLE
CONTRIBUTING.mdの作成について

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#116]
### Problems and suggestions:問題・課題点/提案
Tebukuroへの参加方法やコントリビュートの流れを明確に提示するため、CONTRIBUTING.mdの作成に着手したいと考えてます。

- 参考ページ(他にも良いページがあればご教示下さい)
  - [How to Build a CONTRIBUTING.md](https://mozillascience.github.io/working-open-workshop/contributing/)
  - [atom/CONTRIBUTING.md](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) 

### Countermeasure:対応方法（案）
下記の点を相談したいです。
- [ ] 構成案で修正・追加が必要な項目をご教示下さい
- [ ] 現在皆さんが共有されているコーディングスタイルがあればご教示下さい
- [ ] Sprint BacklogやProduct Backlogに上がっている機能を担当したい場合は、そのIssueにやりたい人が書き込んで宣言する認識で良いですか？
- [ ] PR‪出す時点で一度コミットをrebaseして、レビュー後の修正によるコミットはmerge直前に再度rebaseする認識で良いですか？

下記が構成案です（考えながら書いたので纏まりがないです）

- プロジェクトへのコントリビュートを考えてる人への歓迎メッセージ

- 目次
  - Before Getting Started
  - How to Contribute
  - Styleguides
  - Addtional Notes

- Before getting started
  - Tebukuroプロジェクトの概要・方針
  - プロジェクトへの参加方法
    - issueやpull requestを出す
    - 関連コミュニティに参加したときに相談
  - Tebukuroに関連したコミュニティの紹介
    - Shinosaka.rb、Cherry.rb、Ruby関西 etc.
  - 行動規範(コントリビュータが増えたら作りたい)

- How to Contribute
  - 環境構築
    - リポジトリのforkとclone
    - Zenhub拡張機能のインストール
    - Dockerによる開発環境構築
  - 追加機能の提案
    - Issueを出してメンバーと検討
    - AcceptされたらProduct Backlogに追加
  - バグレポート(まだ無くても良い？)
  - Sprint Backlog、Product Backlogに挙がっている機能の実装
  - PRの作成手順
    - コミットのrebase
    - (PR手順へのリンクまたはコピペ)

- Styleguides
  - Ruby
  - javascript
  - Git Commit Messages

- Addtional Notes (その他、伝えたい事項があれば)

相談事項が多くなって申し訳ないですが、宜しくお願いします！

**Comment by chimame** [comment]
@ytorii さん、回答遅れて申し訳ありません。
また提案型のIssueも大変ありがたく感じております。
大まかには提案通りの`CONTRIBUTING.md`で私は問題ないと思います。

今日 @ogom さんとも話したのですが、 [stateful_enum](https://github.com/amatsuda/stateful_enum)のgemにも書かれている通りのような Contributingについては`Pull requests are welcome`といったように今は広く受け入れたいですね。

環境構築については`Dockerによる開発環境構築`とあるようにwikiに書いているので問題ないはずなのでこれで行きたいですが、 @ytorii さんは実践してみていかがでしたでしょうか。

**Comment by ogom** [comment]
Contributing には絵文字があってもカジュアルでいいかなと思います。例えばこんなのです。

> 😃 Pull requests are welcome on GitHub at https://github.com/shinosakarb/tebukuro.

**Comment by ytorii** [comment]
@chimame さん、@ogomさん
ご回答ありがとうございます！
では絵文字などを使いながら、PRも広く受け入れている事が伝わるように書いてみます。

> 環境構築についてはDockerによる開発環境構築とあるようにwikiに書いているので問題ないはずなのでこれで行きたいですが、 @ytorii さんは実践してみていかがでしたでしょうか。

僕は初めてDockerを使いましたが、Dockerのインストールさえできればwikiの手順で環境構築は簡単に完了できたので助かりました:smile:
最初にbin/dockerを勘違いして、bashのdockerコマンドで実行してハマりましたが。。

**Comment by murajun1978** [comment]
merged 🎉
