### ISSUE TITLE
CIをJenkinsに変更する

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#121]
### Problems and suggestions:問題・課題点/提案
WerckerでCI回してるけど、フロントとバックで別々のコンテナでテストしたい

### Countermeasure:対応方法（案）
* GCPにJenkinsを立てて運用する
* 複数人で管理できるようにする（認証、認可）

**Comment by springaki** [comment]
tebukuro reboot の為、一旦 close します。
