### ISSUE TITLE
Add user authorization to API

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#125]
### Problems and suggestions:問題・課題点/提案
Authorization processing does not exist in the implemented API.

### Countermeasure:対応方法（案）
If the http method is other than "GET" add authorization unconditionally.
- [x] community
- [x] event
- [x] ticket

**Comment by yukihirop** [comment]
やってみてもいいですか？😅

**Comment by chimame** [comment]
どうぞー

**Comment by yukihirop** [comment]
すみません！
SQLを勉強しないと行けないのでこれ他の方に譲って下さい :man_facepalming:

**Comment by gazayas** [comment]
```ruby
before_action :authenticate_user!, only: [:create, :update, :destroy]
```
と言う感じだと思うんですけど、テストはうまく動かないんですね。。。
`rails_helper.rb`に
```ruby
config.include Devise::Test::IntegrationHelpers
```
を追加し、`spec/requests/*_spec.rb`の方では
```ruby
Rails.application.env_config["devise.mapping"] = Devise.mappings[:user]
user.confirm
login_as(user, scope: :user)
```
を書くけど、それでも`401`が返ってきてなかなか解決できません。

動いたらPRを送ります。

**Comment by murajun1978** [comment]
Sign-inしてみてはどうでしょう？

**Comment by gazayas** [comment]
やってみます！

**Comment by chimame** [comment]
Sign-inしてもできないと思います。すいませんが、これは私の方で引き取ります🙇

**Comment by chimame** [comment]
### 全体仕様

- communityはログインしていれば作成できるものとする。

なのでcommunityのみ`before_action :authenticate_user!, only: [:create]`とする。

- community作成と同時にcommunityのownerを登録する。
- communityの修正および削除はownerのみ可能とする。

なので`before_action :authenticate_user!`ではなく、`current_user`を取得しownerでなければ401を返す。

- eventについては`:create`,`:update`,`:delete`はownerのみとする。
- ticketもevnetとほぼ同様とする。
- ticketの購入に関してはログインしていれば可能とする。逆にキャンセルは購入者でなければキャンセルできないとする。

仕様としてはこんなとこでしょうか。adminについては後で追加予定。

**Comment by murajun1978** [comment]
認可までやるの？

**Comment by chimame** [comment]
ownerくらいやけど、それくらいはサクッと入れようかと思ったけど、1issueでは大きい？

**Comment by murajun1978** [comment]
サクッとできるならかまわないよー

**Comment by chimame** [comment]
すべて対応済み
