### ISSUE TITLE
イベントページを表示する

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#131]
### Problems and suggestions:問題・課題点/提案
フロントでイベントページを表示する

表示する項目
* イベント名
* 開催日時
* 開催場所
* イベント内容 (markdown?)
* チケット一覧

**Comment by gazayas** [comment]
おー、イベントの内容はmarkdownでいいですね！

**Comment by springaki** [comment]
この Epic 自体は in progress だから pipeline 移動しますー

**Comment by springaki** [comment]
tebukuro reboot の為、一旦 close します。
