### ISSUE TITLE
イベントページのルーティングを用意する

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#132]
### Problems and suggestions:問題・課題点/提案
イベントページのサーバルーティング（koa）を設定する

e.g.
/events/:id

**Comment by chimame** [comment]
merged https://github.com/shinosakarb/tebukuro/pull/145

**Comment by ogom** [comment]
ワイルドカードのルーティングを追加して、静的ファイルを koa-static で対応すると対応できる？

```
router.get('/(.*)', function (ctx, next) {
  return rootController.index(ctx)
})
```

**Comment by ogom** [comment]
koa は 使用されなくなった。
