### ISSUE TITLE
イベント表示のコンテナを作成する

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#134]
### Problems and suggestions:問題・課題点/提案
イベント表示のコンテナを作成する

reduxとのconnect用コンテナ

**Comment by ytorii** [comment]
イベント表示のコンテナは下記のような構成となるでしょうか？
- renderメソッドにEventとTicketListのコンポーネントを配置（またはrenderメソッドを削除してEventコンポーネントにrenderメソッドを集約）
- mapStateToPropsメソッドでreducerが返すEventモデルをEventコンポーネントのpropsにマッピング
- mapDispatchToPropsメソッドには現時点では設定する項目は無し

**Comment by chimame** [comment]
大体はそんな感じでいいと思います。

>renderメソッドにEventとTicketListのコンポーネントを配置（またはrenderメソッドを削除してEventコンポーネントにrenderメソッドを集約）

EventとTicketListの関係を`children`か`props`でもらうか。`children`の方が拡張性は高いですけど、ここにそんな拡張性を持つ必要はあるのかどうか。

>mapDispatchToPropsメソッドには現時点では設定する項目は無し

さすがにそれはないかと😅
データ取得は必要ですからね。

**Comment by ytorii** [comment]
ご回答ありがとうございます！
確かにComponentとContainerで表示とロジック機能を分けるのは、より複雑なケースで必要になってくる事のようですので、EventコンテナにEventとTicketListのコンポーネントを配置します。
mapDispatchToPropsメソッドについては勉強不足でした:flushed: Eventのアクションをマッピングします！

**Comment by ytorii** [comment]
#174 のPRにて実装済みのため本件closeします。
