### ISSUE TITLE
イベント表示のコンポーネントを作成

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#135]
### Problems and suggestions:問題・課題点/提案
イベント表示に必要なコンポーネントを作成する

#### 作成するコンポーネント
* イベント名
* 開催日時
* 開催場所
* イベント内容

**Comment by ytorii** [comment]
コミュニティのコンポーネントを参考にして、上記の属性を表示するコンポーネントを作成したいと思います。

**Comment by ytorii** [comment]
#157 にてmergeされたため、closeします。
