### ISSUE TITLE
チケット一覧のコンポーネントを作成

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#136]
### Problems and suggestions:問題・課題点/提案
チケット一覧表示に必要なコンポーネントを作成

**Comment by ytorii** [comment]
チケット一覧のコンポーネントもイベントやコミュニティと同様に作成すればよいでしょうか？

**Comment by murajun1978** [comment]
イベントのレスポンスにチケットの情報が含まれます。

```
{
  # event
  "name": "test",
  ...,
  "tickets": [
    {
      "name": "ticket name",
      ...
    }
  ]
}
```

**Comment by ytorii** [comment]
了解しました！では複数のチケットをmap関数を使ってリスト表示する形で作ります。

**Comment by ytorii** [comment]
本Issueは#162のPRにて対応しましたので、closeさせて頂きます。
