### ISSUE TITLE
イベント表示用のアクションを作成

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#139]
reduxのaction creatorを作成する

**Comment by ytorii** [comment]
イベントのaction creatorについても、コミュニティと同様にshowAPIの実行後にcreateEventをdispatchする実装を行うのでしょうか？（基本的にCommunityのaction creatorを参考にして作ることが出来るでしょうか？）

**Comment by chimame** [comment]
そうです。
ただ、そのままコピペしても動くとは思うのですが、DRYじゃないなっと。

**Comment by ytorii** [comment]
例えばshowCommunity内の関数をaction creatorの共通処理として、utils/ActionDispatch.jsのようなファイルにまとめて定義するようにすると良いでしょうか？

**Comment by chimame** [comment]
そんなイメージで作ってくれると非常に助かります！

**Comment by ytorii** [comment]
それでは一旦作ってみます！
APIの作成でも同じ内容のコメントを頂いていたのに申し訳ないです:pensive:

**Comment by ytorii** [comment]
このIssueに関するPRでCommunityのActionも共通処理を使うように変更を加えても良いものでしょうか？もしくはCommunityのActionは別PRで修正した方がいいでしょうか？

**Comment by chimame** [comment]
共通処理は作って、Communityだけは別で作る方法でどうでしょうか？あくまで作った共通処理を使ってEventアクションを作る感じでどうでしょうか。

**Comment by ytorii** [comment]
それではCommunityのActionはそのままにして、EventのActionは新たに作成する共通処理を使う、という形で作ってみます！

**Comment by ytorii** [comment]
#159 のPRがmergeされたため、このissueはcloseします。
