### ISSUE TITLE
イベント表示用のAPIを追加する

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#140]
イベント表示のAPIを追加

endpoint
/communities/:community_id/events/:event_id

**Comment by ytorii** [comment]
この作業はconfig/routes.rbのshallow: trueを削除して、event_controllerとそれに伴うspecファイルを修正する作業でしょうか？もし的外れだったらすみません。。

**Comment by chimame** [comment]
こちらはLabelsを見て頂ければ幸いなのですが、バックエンドAPIの呼び出しをフロントエンドに作成するissueです。なのでReactjs側での対応となります。

**Comment by ytorii** [comment]
ラベルをよく確認していませんでした、すみません。。

**Comment by chimame** [comment]
内容がわからなければドンドン質問して大丈夫ですよ 👍

**Comment by ytorii** [comment]
有難うございます！
front/client/api内のCommunity.jsと同じような、Event.jsの作成（と関連するファイルの修正）とテストを追加する作業、という認識で正しいでしょうか？度々の質問で申し訳ありません。。

**Comment by chimame** [comment]
はい、その認識であってますよ😃

**Comment by ytorii** [comment]
できれば担当したいのですが、下記の前提で合っているでしょうか？
- shallow:trueなので、エンドポイントは/events/:event_id
- 実装するメソッド・テストケースは基本的にCommunityと同じ
  - メソッド：create, get,  show
  - テストケース：createの正常・異常、getの正常
- addressもパラメータとして含める

**Comment by chimame** [comment]
それプラスpatch(edit)、deleteまでできればベストですが、たぶん今の最小リリースではshowさえあればなんとかなります😅

**Comment by ytorii** [comment]
了解しました、それでは作成したらPull Requestします！

**Comment by ytorii** [comment]
PRがmergeされたので本件はcloseさせて頂きます。
