### ISSUE TITLE
イベント会場の住所を追加

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#141]
### Problems and suggestions:問題・課題点/提案
イベントテーブルに開催地の住所がなかった

### Countermeasure:対応方法（案）
attributeを追加
APIのresponseに追加

endpoint
/communities/:community_id/evnets/:event_id

**Comment by springaki** [comment]
Doorkeeper では 255字以内みたいなので、一旦それに合わせておきます。
connpass は不明。

建物名を抜いた長いものは
「秋田県北秋田郡上小阿仁村大字沖田面字小蒲野下タ川原」とかが最長だとかなんとか。
通り名を含む正式な住所でないものでいえば「京都府京都市東山区三条通南二筋目白川筋西入ル二丁目北木之元町」とか。

**Comment by chimame** [comment]
merged https://github.com/shinosakarb/tebukuro/pull/143
