### ISSUE TITLE
イベント照会APIにチケット一覧の属性も合わせて値を返す

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#147]
### Problems and suggestions:問題・課題点/提案
フロントのイベント照会画面ではイベントの情報とチケット一覧を表示する。そのため、現状はRESTに沿っているため、APIを2回呼び出さないとイベント照会画面の全情報は取得できない。
API呼び出しが増えるとhttpサーバに負荷をかけることとなってしまう。

### Countermeasure:対応方法（案）
イベント照会APIでは該当イベントの属性のみを返しているがそれ紐づくチケット一覧（tickets）も合わせて返す。それによりAPI呼び出し回数を減らしhttpサーバの負荷を低くする。

チケット属性の属性は以下
- チケット名
- 価格
- 枚数（残枚数）
- 購入可能な開始日時（表示する必要ないかも）
- 購入可能な終了日時

**Comment by gazayas** [comment]
これは、チケットの情報をイベントのコントローラに流す感じですか？

**Comment by murajun1978** [comment]
EventのレスポンスにTicketの情報も含めるってことですね。
こんな感じになると思います。
```
{
  'name': 'event name',
  'description': 'event description'
  ....,
  tickets: [
    {
      'name': 'ticket name',
      'cost': 0,
      ...
    }
  ]
}
```

**Comment by gazayas** [comment]
[Jbuilder](https://github.com/rails/jbuilder)は良さそうです。
導入していいですか！w
Gemfileでコメントアウトしてありますね

**Comment by gazayas** [comment]
```
def show
    render json: @event, include: @event.tickets
end
```

な感じがいかな。テストはうまく動いてないけどいじってみます 😄

**Comment by springaki** [comment]
@gazayas さんが 実装中ってコトであってますかー？ 😸

**Comment by gazayas** [comment]
はい！がんばります

**Comment by ytorii** [comment]
#164 のPRがmergeされたため、このIssueはCloseします。
