### ISSUE TITLE
ユーザが参加登録済みのチケットをキャンセルできるようにする

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#155]
### Problems and suggestions:問題・課題点/提案
ユーザが参加登録済みのチケットをキャンセルできるようにする

#### まずやること
- 無料チケットのみ考える
- キャンセルメールの配信 (必要かどうか未検討?)

#### 今はやらないこと
- 有料チケット (決済キャンセル)

#### エンドポイント
```
DELETE /subscription/tickets/:id
```

**Comment by murajun1978** [comment]
エンドポイントはこれで

https://github.com/shinosakarb/tebukuro/issues/168#issuecomment-288127340

**Comment by murajun1978** [comment]
対応ずみの為クローズ
