### ISSUE TITLE
Dockerで開発環境を構築

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#16]
すぐに開発できるようにDockerで開発環境を構築する

開発環境が変われば都度修正していく

**Comment by yukihirop** [comment]
# docker-compose upするまでの道のり (使用PCはMac前提)
```
docker-machin create --driver virtualbox  default
```
 ⇒ `default` は別になんでも良い。これでvirtubalboxにdefaultという名前でDockerホストが作成される
　  (昔はLinuxVMのboot2dockerというVMが使われていたらしいが今は非推奨とのこと)

```
docker-machine env  default
```
 ⇒ 環境変数を設定する。Docker で対象マシンに対して通信する必要があるため必要となる。
 ⇒支持に従って、`eval $(docker-machine env default` を実行すればよい。
 ⇒`eval` の設定は新しいタブを開いたり、再起動の度に実行する必要がある。

### 新しいタブを開いたり、再起動の度に、`eval $(docker-machine env default`　したくない場合
```
vi ~/.zshrc (もしくは vi ~/.bash_profile)
eval  "$(docker-machine env default)"
```
もしくは一行で以下のように書けば追加される。
```
export eval "$(docker-machine env default)" >> ~/.zshrc
source ~/.zshrc
# もしくは
export eval "$(docker-machine env default)" >> ~/.bash_profile
source ~/.bash_profile
```

### docker-machine(VMの名前はdefault) 起動
```
docker-machine start default
```
```
docker-machine status default
# runningになればOK
```

## docker-composeの起動
カレントディレクトリにDockerfileとdocker-compose.ymlがあることを確認して
```
docker-compose up
```
⇒ Dockerfile(textファイル)が実行されていく。
⇒  [Add settings for docker #15](https://github.com/shinosakarb/tebukuro/pull/15 "Add settings for docker #15") で書いてあるコマンドが使える様になる。

## dockerの理解を助けてくれそうな資料
・[今だからこそ知りたい Docker Compose/Swarm 入門](http://www.slideshare.net/zembutsu/introduction-to-docker-compose-and-swarm "今だからこそ知りたい Docker Compose/Swarm 入門")

**Comment by yukihirop** [comment]
dockerに関して図解してあってわかりやすい資料
[今だからこそ知りたい Docker Compose/Swarm 入門](http://www.slideshare.net/zembutsu/introduction-to-docker-compose-and-swarm, "今だからこそ知りたい Docker Compose/Swarm 入門")

**Comment by murajun1978** [comment]
merged
