### ISSUE TITLE
誰がTicketを購入したかの管理テーブルを作成する

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#167]
### Problems and suggestions:問題・課題点/提案
Ticket購入したユーザを管理するテーブルが存在しない

### Countermeasure:対応方法（案）
以下のattributesでTicketUsersテーブルを作成する

- ticket_id
- user_id

**Comment by chimame** [comment]
名称は`TicketUsers`より`Subscriptions`の方がいいかも

**Comment by murajun1978** [comment]
`Subscriptions` って抽象的すぎないかな 🤔

なんの `Subscriptions` かわからない

**Comment by chimame** [comment]
確かに。`TicketSubscriptions`？

**Comment by murajun1978** [comment]
うん、そっちがいい 👍
