### ISSUE TITLE
Ticket購入のAPIを作成する

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#168]
### Problems and suggestions:問題・課題点/提案
APIにTicket購入のAPIが存在しない

### Countermeasure:対応方法（案）
以下のエンドポイントでAPIを作成する

`POST /tickets/:ticket_id/subscription`

ユーザの特定にはクライアントから送られてくる(devise-)tokenで判定すること

**Comment by chimame** [comment]
エンドポイントは以下で

`POST /tickets/:ticket_id/ticket_subscriptions`

**Comment by murajun1978** [comment]
同じイベントのチケットを複数申し込みできないようにするほうが良いな

**Comment by murajun1978** [comment]
エンドポイントは `POST /tickets/:ticket_id/subscriptions` で良さそう

**Comment by murajun1978** [comment]
ちょっとエンドポイント考えます

`POST /tickets/:ticket_id/subscriptions`

delete ???

**Comment by murajun1978** [comment]
`DELETE /subscription/tickets/:id`

**Comment by chimame** [comment]
こうよね？(たぶん今のところこの２つだけのはず)

```
POST /subscription/tickets/:id
DELETE /subscription/tickets/:id
```

いいと思います。:+1:
