### ISSUE TITLE
イベント照会APIに追加したチケット一覧に購入済み判定可能な属性を追加する

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#169]
### Problems and suggestions:問題・課題点/提案
ユーザがTicketを購入した場合、以降ユーザへはTicketを購入済みと通知する必要があるが
現在のAPIはその項目が存在しない。

### Countermeasure:対応方法（案）
購入済みかどうかの属性をJSONの返り値に追加する

**Comment by springaki** [comment]
tebukuro reboot の為、一旦 close します。
