### ISSUE TITLE
利用するCI関連のサービスを決める

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#17]
テストやデプロイなどを自動化したいので利用するサービスを決める必要がある。
良さげなサービスがあれば提案してください。

#### Test 💉   & Build  🚀 
* [CircleCI](https://circleci.com/)
  * concurrency 1
* [wercker](http://www.wercker.com/) 
  * concurrency 2
* [Travis CI](https://travis-ci.org/)
  * concurrency ??

#### Auto code review 👮
* [SideCI](https://sideci.com/ja/why_sideci?)

**Comment by chimame** [comment]
これどうなんやろ
[DEPLOYBOT](https://deploybot.com/)

**Comment by murajun1978** [comment]
テストのCIツールは `wercker` 、コード 👮  は `SideCI` を使うことにします

**Comment by murajun1978** [comment]
build && deploy はおそらく `wercker` のスクリプトで実行

テストも書いてくれているのでCI回す

**Comment by springaki** [comment]
コレは今 @murajun1978 さんが設定中なのかなー ✨

**Comment by murajun1978** [comment]
そうですねー。でも、早い者勝ちですのでー

**Comment by murajun1978** [comment]
↑ いま見返して、言葉足らずな気がしたので追記ー  :pencil2:

僕がやる予定にはなっていますが、チャレンジしたいメンバーがいれば遠慮なくやってみてください。

PRが早い者勝ちですー（別にかぶっても問題なしです

**Comment by chimame** [comment]
`wercker`のリンク先はわざと？それと`Travis CI`ってshinosakarbのオーガニゼーションのアクセスない人には無理じゃない？

**Comment by murajun1978** [comment]
失礼、werckerのリンク先を修正しましたよん

**Comment by murajun1978** [comment]
merged #38

**Comment by murajun1978** [comment]
#121 Jenkinsで対応する
