### ISSUE TITLE
SNSアカウントを用いたログイン機能を実装する

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#18]
まずは本システムの構造（SPAでの）ログイン機能の実装案を以下に記載します。
意見お待ちしておりますので、どしどし意見を下さい。

#### 前提
 - SNSアカウントを用いた認証を行う（本システム自体にパスワード等は保持しない）

そこで以下のように考えてみました。
#### 実装案
 - 認証時に該当SNSにリダイレクトする
 - 認証後のコールバックをBackendにし、そこでJSON Web Token(以後：JWT)を発行する。それ以降はBackendにJWTを渡ものとする（ログイン判定をする
 - BackendからJWTを送ることができないので、Nodeを経由して渡す（どうやって？ページに埋め込む？）
 - Frontendは送られたJWTを保存する（保存先はCookie or local storage。オススメはCookie）

JWTって何って方は[こちら](http://qiita.com/kaiinui/items/21ec7cc8a1130a1a103a)

#### 実装イメージ
![image](https://cloud.githubusercontent.com/assets/7520815/20296780/1d58b9b0-ab50-11e6-8b1d-5ab0349e127c.png)

#### 未調査事項
 - (Railsが)APIモードでredirectできたっけ？
 - JWTをどうやってFrontendに返そうか？（Railsで生成するのは必須）
 - JWT保存先をCookieにオススメしたのはlocal storageを選択した場合はSSRが不可能？

以下シーケンス図メモ
```
@startuml

actor User

User -> Backend : Login page view Request
activate User

activate Backend
Backend -> GitHub : Redirect Login Request
deactivate Backend
activate GitHub
User <-- GitHub : Login page Response
deactivate GitHub
deactivate User

User -> GitHub : Login  Request
activate User
activate GitHub
GitHub -> GitHub : Authentication
Backend <-- GitHub : Completion of authentication request
deactivate GitHub
activate Backend
Backend -> Backend : create User(when initial user)
Backend -> Backend : create JSON Web Token
Node <- Backend : Redirect Login Start Page Request(add JWT)
deactivate Backend
activate Node
User <-- Node : Login Start Page(add JWT)
deactivate Node

User <- User : Save JWT(Cookie or local storage)
deactivate User

User -> Backend : create Community Request(send with JWT)
activate User
activate Backend
Backend -> Backend : create community
User <-- Backend : Complete the creation
deactivate Backend
deactivate User

@enduml
```

**Comment by murajun1978** [comment]
見てる 👀   
* [Auth0](https://auth0.com/docs/quickstart/backend/rails)

**Comment by springkuma** [comment]
すいません、このフローは OAuth2 でもらったAccessトークン(か、もしかしたらuser_id)を、
backendとfrontendの間の改竄を防ぐというようなフローになりますか？
(実は、最初 OAuth2 とか OpenIDのトークンの署名の話かと思って迷走してしまった…)

**Comment by chimame** [comment]
>backendとfrontendの間の改竄を防ぐというようなフローになりますか？

その役割もあります。
それと合わせてログイン状態を管理できるというのが今回のメインです。
詳しくは https://github.com/shinosakarb/tebukuro/issues/18#issue-186221269 に書いているリンクを参照して下さい。

**Comment by springkuma** [comment]
あ、そこはわかってるつもりです。改ざんできないから、一度認証したトークンを
クライアントに渡した後も信用できる状態で受け渡しできて、それをもってログイン状態を
管理できるって話ですよね。(僕の日本語がややこいですが…)

**Comment by springkuma** [comment]
Django だとまさにこんな感じか。
[REST framework JWT Auth](http://getblimp.github.io/django-rest-framework-jwt/#overview)

**Comment by yukihirop** [comment]
僕でも理解できそうなJWTの記事見つけました。
http://blog.mitsuruog.info/2014/08/jwtjson-web-tokenwebapicredential.html

**Comment by chimame** [comment]
たぶんお二人の認識はあっていると思います。

>一度認証したトークンを
クライアントに渡した後も信用できる状態で受け渡しできて、それをもってログイン状態を
管理できるって話ですよね。

言語化するっていうのは難しいですね（笑）それで合ってます。
JWTの発行はFrontend(Node)側でもできて、それをBackend(Rails)側で検証ってこともできるけど、秘密鍵を両方に設定しないといけないのが嫌なんで発行と検証をBackend側によせています。

**Comment by murajun1978** [comment]
frontend -> [OAuthリクエスト] -> 
backend -> [認証ページへリダイレクト] -> 
認証ページ -> [callback] -> 
backend -> [access_tokenからUser特定(find or create)] -> [JWT生成] -> [parameterにJWTをセットしてリダイレクト] -> 
frontend -> [cookieへ保存] -> AuthorizationにJWTをセットしてAPIを利用

多分これでできるけど、JWTの渡し方が気に入らない

**Comment by murajun1978** [comment]
ちょっとサンプル作ってみよ  :smiling_imp:

**Comment by chimame** [comment]
サンプルを作ってみましたー
https://github.com/chimame/tebukuro/tree/auth_sample

```
bin/docker s && cd client
npm start
```

で`localhost:4000`です。環境変数を使ってます。`config/initializers/omniauth.rb`を参照して下さい。

**Comment by murajun1978** [comment]
https://github.com/lynndylanhurley/redux-auth/blob/master/docs/api-expectations/oauth-sign-in.md

**Comment by chimame** [comment]
Popupか…好みではないけどありっちゃありか。
てかJWT前提みたいになってるけど、これに異論はないのかな？

**Comment by murajun1978** [comment]
redux-atuhでは別windowで認証画面を表示しておいて、認証されるまでclient側でlistenするみたいね。
JWT自体には問題ないと思うよ

**Comment by murajun1978** [comment]
JWTって一度発行すると取り下げ(remove)るの面倒くさいのかな？
であれば、デメリットになるかもしれないね。

**Comment by springkuma** [comment]
ちょっと面倒くさそうな感じがします。 > 取り下げ
有効期間を適切な範囲で短くするとかくらいかな。

**Comment by chimame** [comment]
実装イメージがよくなかったので修正しておきました。

**Comment by murajun1978** [comment]
`devise_token_auth` 使うとリクエストするたびに `access-token` 変わるし、 JWTは必要になってからでもよいかも
例えば、Providerを自前で用意するときとか

**Comment by chimame** [comment]
忘れてたのですが、redux-authでのサンプルです。（client側が未完成で、ログイン状態をcookieに保存できていません）
https://github.com/chimame/tebukuro/tree/redux_auth_sample

**Comment by gazayas** [comment]
もしJSONとdeviseを使うんだったら<a href="http://qiita.com/k-shogo/items/6d687c38b0f7b3ade6f5" target="_blank">この記事</a>はいいかな。

後はdeviseの設定なんですが、Confirmableのオプションを有効にすると思いますが、Lockableとかはどうしますか？
一旦設定してから新しい属性を加えたり変更したりするのは(僕の経験では)ちょっと厄介なので前にそちらへんをしっかりと決めたいなと思います。
Omni-authと連携するのはしたことがないので、詳しくなくてすみません。

**Comment by chimame** [comment]
merged https://github.com/shinosakarb/tebukuro/pull/119
