### ISSUE TITLE
サイトのトップページを作成する

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#19]
デザイナーさんは現状いないので、Bootstrapでもなんでもとりあえずトップページを作成しましょう。
「こんなんがいいなー」「画面にはこれを配置してほしいな」とざっくばらんに意見下さい。

ちなみに自分はこんなのが好み
http://www.kokubunji-centralgolf.jp/

下はお知らせとバナーまでで、その下にはイベント一覧でも表示する感じ？

**Comment by tono0123** [comment]
TOPページに必要な情報
・ログイン
・お知らせ？
・イベント一覧（イベントタイトル、アイキャッチ）
とかですかね？？

> http://www.kokubunji-centralgolf.jp/
どうでもいいことですけど、ここ実家の近所ですw
このサイト綺麗ですね。

https://www.synergy-marketing.co.jp/
個人的にはこんなかんじがいいと思います

**Comment by murajun1978** [comment]
ちなみにフロントは Express.js 等のframeworkは使わない感じ？

**Comment by chimame** [comment]
Express.jsくらいは使うかな。 #18 の絡みもあるので。

**Comment by murajun1978** [comment]
Express以外を試したいかん

**Comment by chimame** [comment]
>Express以外を試したいかん
なるほど…ならば

- [sails](http://sailsjs.org/)
- [Meteor](https://www.meteor.com/)

Express以外となると候補としては上記の2つかな。
sailsは王道？MVCのガチやね。Meteorは攻めた感じになるぞ。

**Comment by murajun1978** [comment]
こんなのは？
* [Koa](https://github.com/koajs/koa)
* [Hapi](http://hapijs.com)

**Comment by chimame** [comment]
どれがどんな特徴を持ってるか調べないといけないな。
ちなみにGitHubスター数は以下
・Meteor:35,748
・sails:15,727
・Koa:12,414
・Hapi:6,875

Koaが以外とあるのはびっくりしたな。固いとこでMeteorで行きたいとこやけど何分どれも経験がないし、わからんな。

**Comment by chimame** [comment]
Meteorは攻めた感じではなく、今は王道って感じか。特にReact使うなら尚更。
Railsのスター数と並ぶのはすごいな。
公式ドキュメントもしっかりしてるし、Reactを正式にサポートしてるぽいので、Meteorでいきたいのが自分の意見。

sailsはまぁ名前の通りRailsと…
Koaもtjが関わってるから関心がないといえば嘘になる。けど情報が何分少ない。（日本語だと）
Hapiは…

若干論点がズレてきてるから別issueにする？

**Comment by murajun1978** [comment]
そうだね、別のissueにしよっか

**Comment by murajun1978** [comment]
move to #20 about using framework.

**Comment by chimame** [comment]
* カレンダー
* イベント検索へのリンク？
はほしい。

**Comment by ogom** [comment]
トップページはできるだけコンテンツは設置しないで、プロダクトのコンセプトが解るものがほしいです。あとテブクロの名前を付けているので、暖かい感じのカラーやディティールになると思っています。

**Comment by ogom** [comment]
トップページは、イベントをインクリメンタルサーチでヒットしたイベントをリストアップする機能があるだけでいいかも。実際にイベントの告知は SNS を使うから、サーチ機能はマストではない。
マストなのは、サインアップとサインインくらいかな？

**Comment by murajun1978** [comment]
トップページはコンセプトのみでOKです。
Sign in への誘導だけでいいかな。

### Tebukuroのコンセプト
* モバイルフレンドリー
* モバイルのみで簡単にコミュニティやイベントを公開できる
* イベント中の写真をアップロード（SNS通知）
* コミュニティサイトに申し込みページを簡単に追加できる
* プライベートなイベントを公開できる
* 基本タダ

**Comment by springaki** [comment]
tebukuro reboot の為、一旦 close します。
