### ISSUE TITLE
CIを構築する

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#198]
- [x] [Client](https://github.com/shinosakarb/tebukuro-client)
- [ ] [API Server](https://github.com/shinosakarb/tebukuro)

**Comment by murajun1978** [comment]
Client is done! https://github.com/shinosakarb/tebukuro-client/pull/4

**Comment by murajun1978** [comment]
とりあえずbackendはWerckerのままでOK

**Comment by murajun1978** [comment]
フロントエンドは masterとそれ以外のデプロイで環境変数を変えないといけない（まだやらない

**Comment by murajun1978** [comment]
一旦close
