### ISSUE TITLE
JSON-APIを外す

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#199]
@ogom 理由書いてください

**Comment by ogom** [comment]
[AMS](https://github.com/rails-api/active_model_serializers/tree/0-10-stable)のGemでRailsのJSONのレスポンスを[JSON API](http://jsonapi.org/)にすることで、リクエストの回数やレスポンスにdataのtypeを含めることでクライアントの利便性の向上を期待したが、開発初期ではRails wayから外れることやJSON APIにすることでクライアントの開発コストが高くなるのでJSON APIを外すことを決定しました。

**Comment by springaki** [comment]
@ogom Thanks. description 直接書き換えちゃっていいですよ 😊

**Comment by ogom** [comment]
@springaki 今度から直接書き換えます 😄
