### ISSUE TITLE
Nodejs(Frontend)の使用フレームワークを決める

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#20]
別issueからの議論展開です https://github.com/shinosakarb/tebukuro/issues/19#issuecomment-257592900

現状Nodejsで使用するフレームワークが未決定であるため決めたいと思います。
そこで下記のフレームワークを案として検討を行います。参考に()内にGitHubのスター数を記載してます。ちなみにRailsは33,240です。
 - [Meteor](https://www.meteor.com/)(35,748)
 - [sails](http://sailsjs.org/)(15,727)
 - [Koa](https://github.com/koajs/koa)(12,414)
 - [Hapi](http://hapijs.com/)(6,875)

もちろん上記以外のフレームワークでも検討は可能です。

**Comment by chimame** [comment]
Meteorを使ってみようと思ったけど、簡単に動かせなかったので検証は後回し。（他のがよかったら検証すらしない）
それにこいつはnpmでいれない分 `/usr/local/bin/meteor` を作るからちょっとお行儀が悪いな。
ついでにDocker内で試そうとも思ったけど、これも何か問題があって動かないぽい。

**Comment by chimame** [comment]
KoaはVer2があるのか。ただし、midleware等が完全にまだVer2対応されていない。
https://github.com/koajs/koa/wiki

**Comment by yukihirop** [comment]
expressが色々情報が多そうな気がする
http://qiita.com/nakahashi/items/15c016ff8beacd014fe4

**Comment by chimame** [comment]
色々みてみましたが、MeteorかKoaのどちらかでいこう。

**Comment by murajun1978** [comment]
んじゃ、Koaで

**Comment by murajun1978** [comment]
Meteorはでかすぎる

**Comment by chimame** [comment]
特に異論はなし :ok_man:

**Comment by murajun1978** [comment]
Koaで決定
