### ISSUE TITLE
参加者がイベントに参加登録する

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#204]
名前入力だけ。認証とかはまだやらない。
調整さんみたいに名前入力だけでOKのイメージ

**Comment by chimame** [comment]
バックエンド側でやらないといけないこと

- [ ] Eventに紐づく参加者のスキーマ作成
- [ ] ルーティングからモデル、コントローラと一式用意

**Comment by ytorii** [comment]
参加者のスキーマおよびルーティングについて認識を合わせたいと考えています。
とりあえず以下の様なものを想定していますが、ご指摘・ご意見をお願いします。
#### バックエンド
##### スキーマ
- テーブル名： `participants`
- カラム：
  -  `name`  (string、not null)
  -  `event_id`  (integer、not null)
- インデックス：
  -  `event_id`  

doorkeeper や connpass で participants というエンドポイントがあったので参考にしました。

##### ルーティング
`routes.rb`で ↓ のような感じ：
````
resources :events do
   resources :participants, only: :index, :create
end
````

#### フロントエンド
##### エンドポイント
- 登録： `/events/:event_id/participants`  (POSTメソッドで event_id、name パラメータを送信)
- 一覧： ` /events/:event_id/participants`  (GETメソッドで event_id パラメータを送信)

**Comment by springaki** [comment]
@ytorii LGTM 特に違和感ないです。

**Comment by ytorii** [comment]
フロントエンド／バックエンド共に作業を完了したため、close します！
