### ISSUE TITLE
クライアントサイドのルーティング

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#207]
### Question contents:質問内容
イベントの新規・詳細・編集ページを作成するには、クライアント側でのルーティングおよびファイルの配置について検討する必要がある。

### Problems and suggestions:問題・課題点/提案
現状ではpages直下に全てのページを配置することになり、今後ページの増加に伴って管理しづらくなる事が懸念されている。可能な限りNext.jsのデフォルトの機能を利用して、構造化されたルーティングを設計する。

### Countermeasure:対応方法（案）
pagesディレクトリを以下の構成とすることで、ルーティングの構造化を図る。
 
````
pages
├── index.js
└── event
    ├── new.js
    ├── show.js
    └── edit.js
````

- 新規イベントを作成する場合は、`/event/new` にアクセスして、`event/new/.js`が表示される
- 詳細ページへは、 `/event/1`にアクセスして、`event/show.js`が表示される
（実際には`/event/show?id=1`へのアクセスで、`/event/1`にマスキング）
- 編集ページへは、 `/event/1/edit`にアクセスして、`event/edit.js`が表示される
（実際には`/event/edit?id=1`へのアクセスで、`/event/1/edit`にマスキング）

クライアント側で`<Link>`要素からアクセスできることを確認している。

### 補足 
- 各URLへの直アクセス方法は現在調査中ですが、基本的には server.js を作成してルーティングを設定して実装する形になります。（express.js の導入が必要かも）

- ディレクトリ構成は、eventディレクトリ直下にnew.js、show.js、edit.jsを配置~~してもいいかなと思ってます~~する。

**Comment by murajun1978** [comment]
> ディレクトリ構成は、eventディレクトリ直下にnew.js、show.js、edit.jsを配置してもいいかなと思ってます。

これに 👍

**Comment by ytorii** [comment]
ではその内容で pages 配下を修正します！

**Comment by murajun1978** [comment]
お願いしまっす 🙏

**Comment by ytorii** [comment]
修正しましたー
https://github.com/shinosakarb/tebukuro-client/pull/20

**Comment by ytorii** [comment]
PR #20 でmerge済みのため、closeします。
