### ISSUE TITLE
APIのエラーメッセージの仕様について

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#214]
### Question contents:質問内容
APIのエラーメッセージの仕様について、現時点（Epic: イベントを作成する）および将来的な仕様を、フロントエンド／バックエンドを含めて認識を合わせたいと考えています。

### Problems and suggestions:問題・課題点/提案
11/2での打ち合わせ内容を反映して、エラーメッセージの仕様を以下の通りと認識しています。

- エラーが発生する主なケースの前提
  - バリデーションエラー等でステータスコード 422 となる
  - ページが存在せずステータスコード 404 となる
  - 上記のうち、404 エラーではフロントエンドで[Nextjsデフォルトのエラーページを表示する](https://github.com/zeit/next.js/#reusing-the-built-in-error-page)

- 現時点（Epic: イベントを作成する）
  - バックエンド
    - コードは現状のまま、次のようなエラーメッセージを返す： `{  "name": [ "を入力してください" ] }`
  - フロントエンド
    - 受け取ったエラーメッセージを配列形式にして、Error オブジェクトに格納して返す

- 将来
  - 現状の仕様では i18n への対応が困難なので、各エラーごとにエラーコードを割り当てて、フロントエンド／バックエンドで共有する（詳細は #108 のIssue で検討）
  - バックエンド
    - 各エラー毎に割当てられたエラーコードを返す
  - フロントエンド
    - 返ってきたエラーコードから、フロントエンドの環境に対応した言葉でエラーメッセージを作成する

### Countermeasure:対応方法（案）
フロントエンドの API は、旧tebukuro でやっていたような実装になるかなと思ってます。（コード自体はもう少し違った書き方にするかもしれませんが）

旧tebukuro での実装：
````
const onFailure = (error) => {
  let errorMessages = []

  if (error.status === 404) {
    errorMessages = ['Not Found']
  } else {
    errorMessages = createErrorMessages(error.response.body)
  }
  throw new ApiResponseError(errorMessages)
}

const createErrorMessages = (errorBody) => {
  let errorMessages = []

  for (var key in errorBody) {
    // skip loop if the property is from prototype
    if (!errorBody.hasOwnProperty(key)) continue;

    errorBody[key].forEach((error) => {
      errorMessages.push(`${key}${error}`)
    })
  }

  return errorMessages
}
````

認識が異なる、あるいは変更した方が良い点などご意見をお願いします！

**Comment by murajun1978** [comment]
@ytorii Promiseでは、throw するのではなく Promise.reject してほしい。
なぜなら、他の例外と区別したいからです。
意図して、catchに流したい場合は Promise.rejectを使ってください :pray:

**Comment by ytorii** [comment]
了解しました、ありがとうございます！

**Comment by ytorii** [comment]
API の PR #13 がマージされたため、クローズします。
