### ISSUE TITLE
イベント定員設定ができるようにしたい

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#220]

**Comment by ytorii** [comment]
やること一覧:
- フロントエンド
  - [ ] イベント作成ページで定員の入力フィールドを追加
  - [ ] イベント詳細ページで `申し込み人数／定員`を表示

- バックエンド
  - [ ] Event テーブルに定員カラムを追加
    - カラム： `quota` (number, not null, １以上１０００以下の整数)
  - [ ] Event コントローラの strong_paramters に `quota` を追加
  - [ ] Event シリアライザの出力に `quota` を追加

**Comment by murajun1978** [comment]
この1000以下ってなにか意図があるのですか？

**Comment by ytorii** [comment]
1000以下に大きな意図はありません。
ただ上限を設けないのも危険かなと考えて、最大1000人程度の受け入れ枠があれば十分かなと考えています。

**Comment by murajun1978** [comment]
> ただ上限を設けないのも危険かなと考えて

どんなことを想定しています?

**Comment by ytorii** [comment]
あまりありえないかもしれませんが、かなり大きな人数（1,000,000とか）を設定して、大量に参加登録することでリソースが圧迫される攻撃などです。
最終的には、ユーザー認証も追加しますし、あまり現実的ではないかもしれませんが。。
現時点で上限は設ける必要は無いでしょうか？

**Comment by murajun1978** [comment]
RailsのバリデーションくらいならOKですかねー
スキーマでlimit指定してしまうとやり過ぎな気もしますー :smile:

**Comment by ytorii** [comment]
了解しました！では Rails のバリデーションで設定します。

**Comment by murajun1978** [comment]
お願いしますー :pray:

**Comment by ytorii** [comment]
フロントエンド／バックエンド共に作業が完了しましたので、close します！
