### ISSUE TITLE
イベント定員を設定して、キャンセル・キャンセル待ち・繰り上がりなどの流れを作りたい

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#221]
- 全ユーザ100人くらいのつもりでまずは実装する。パフォーマンス要件は緩めで。
- 定員はEvent テーブルのカラムとする
- キャンセル待ちは参加登録者のTop10（定員10人の場合）に入っているかどうかで判定する

see #230

**Comment by murajun1978** [comment]
Thanks!

**Comment by ytorii** [comment]
以下の順番で実装しようと考えています。

- #220 イベント定員の設定： 
  - 定員カラムを Eventテーブルに追加、イベント作成時に定員を設定できるようにする
- #223 参加キャンセル機能の追加：
  - 参加者一覧でキャンセルボタンを追加し、参加者を削除できるようにする
- #222 キャンセル待ち機能の追加：
  - 定員を超えた後は、参加登録ボタンを「キャンセル待ちに登録」と表示する
  - 定員を超えた後は、参加者の登録時にキャンセル待ちとなるのかを判定する
  - キャンセル発生時に、キャンセル待ちの参加者が繰り上がったかを判定できるようにする

**Comment by springaki** [comment]
LGTM

できれば、参加登録後に "参加登録完了しました", "キャンセル待ちです" が出せれば嬉しいかなー

**Comment by ytorii** [comment]
作業一覧に追加しました:smiley:

**Comment by springaki** [comment]
@ytorii ありがとうございます !

**Comment by murajun1978** [comment]
キャンセルを実装するにはユーザを特定する必要がある :thinking:

**Comment by ytorii** [comment]
現時点では、以下のように誰でも削除できる状態を考えていました。
- 参加者一覧に並んでいる参加者名の横にボタンを配置
- ボタンが押された参加者のIDをパラメータにして、`delete` メソッドをバックエンドに送信

**Comment by murajun1978** [comment]
遠回りしていなか心配ですが、UIくらいなので大丈夫かなー

**Comment by ytorii** [comment]
最終的には、ユーザー登録および認証を追加するので、遠回りは確実ですね。。
このエピックより先に、ユーザー関連の機能を追加しますか？

**Comment by murajun1978** [comment]
同時にやってあとでmergeしちゃいましょう

**Comment by ytorii** [comment]
了解しました！

**Comment by ytorii** [comment]
この Epic に関する全ての作業が完了したので close します。
