### ISSUE TITLE
キャンセル待ちができるようにしたい

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#222]
- 定員を超えた登録者はキャンセル待ち状態になる
- 定員枠内の人がキャンセルしたら繰り上がり処理が行われる

**Comment by springaki** [comment]
現時点での "繰り上がり処理" とはイベントページを再表示した時にキャンセル待ちの人が参加状態に見えればOK

**Comment by ytorii** [comment]
バックエンドでのキャンセル待ち判定の実装方法について、以下のように検討しています。
実装方法、クラス・メソッド名などについてご指摘あればお願いします！

- 判定するタイミング：
  - イベントへの参加登録時（Participant Model の after_create）
    -  キャンセル待ち登録の通知のため
  - 参加登録のキャンセル時 （Participant Model の after_destroy）
    - 繰り上がりの確認および通知のため

- 判定方法：
  - 参加登録者（Participant）のTOP１０（定員 １０、作成日時順）に対象の参加者が含まれているか

- ロジック構成：
  - キャンセル待ちを判定するクラス `ParticipationWrapper` （仮称） を作成、Participant Model から呼び出す	
  - `ParticipationWrapper` では public クラスメソッド `after_create`、`after_destroy` を実装
  - それらのメソッド内で判定を行うprivate クラスメソッド `is_waiting_for_cancel?` を呼び出す
  - 現時点では判定のみ行い、通知などの具体的な処理は行わない

以下のようなコードを考えています：
- participant.rb
````
.....
after_create ParticipationWrapper
after_destroy ParticipationWrapper
.....
````

- participation_wrapper.rb
````
.....
def after_create(participant)
  is_waiting_for_cancel?(participant)
  (...subsequences like sending a mail)
end

def after_destroy(participant)
  is_waiting_for_cancel?(participant)
  (...subsequences like sending a mail)
end

private 

def  is_waiting_for_cancel?(participant)
  (...check this participant is included in the top list)
end
.....
````

**Comment by murajun1978** [comment]
callbackを使うと一気にロジックが複雑になってしまいますね、、

- 参加登録の完了時にキャンセルかどうかの値をレスポンスに含め、フロントエンドでキャンセル待ちかどうかを判定（メッセージを切り替えとか）する
- キャンセルはフロントでなにもする必要がないので修正なし
- 通知系は非同期処理にする (Controllerから呼び出し)

僕のアイディアですが、上記のように実装するとシンプルになってバグが混入しにくいかなと思いました
それぞれ独立してテスト可能です

**Comment by ytorii** [comment]
ありがとうございます！確かにロジックが階層構造を持つこともあり、複雑ですね。。

では、以下のようなイメージでしょうか？
- キャンセル待ちかどうかの判定は Serializer で行い、値を attribute に追加
- フロントエンドではキャンセル待ちかどうかは、通知メッセージで確認する
（参加者一覧でキャンセル待ちかどうかの表示はなし）
- Controller での非同期処理は Sidekiq を使用

**Comment by ytorii** [comment]
[フロント側のPR] （https://github.com/shinosakarb/tebukuro-client/pull/43）がマージされたので close します。
