### ISSUE TITLE
イベント参加をキャンセルしたい

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#223]

**Comment by ytorii** [comment]
やること一覧（現状では、ユーザーは考慮せずに作成する）:
- フロントエンド
  - [ ] 参加登録をキャンセルする、`CANCEL_REGISTRATION` アクションの追加
  - [ ] Event、Participant の Reducer で Store から対象の参加者を削除する処理を追加
  - [ ] イベント詳細ページに参加キャンセルボタンおよびアクションを追加

- バックエンド
  - [ ] Partcipant コントローラに `destroy`メソッドを追加
  - [ ] `route.rb` の `participants` で `destroy` を許可し、 `/events/:event_id/participants/:id (DELETE)` のルーティングを追加

**Comment by ytorii** [comment]
フロントエンド／バックエンドともに作業が完了したので Close します。

**Comment by murajun1978** [comment]
ありがとうございますー :smile:
