### ISSUE TITLE
イベントの定員およびキャンセル待ちの追加に関するDB設計

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#230]
### Question contents:質問内容
イベントの定員およびキャンセル待ちを追加するにあたっての、DB設計について検討したいと考えています。

### Problems and suggestions:問題・課題点/提案
以下の作業を想定しています。
- Event テーブルに定員のカラムを追加もしくは Ticket テーブルを追加
- キャンセル待ちの状態を何らかの方法で表現

#### ■Event テーブルに定員カラムを追加
  -  `quota`  (number、not null) カラムを追加
  -  定員の下限は1、上限は無し(もしくはとりあえず1000など)？

#### ■キャンセル待ちの判定
DBでキャンセル待ち状態を保存せず、必要な時に定員に照らし合わせて判定
- 参加登録のTop１０（定員１０人の場合）を参加できる人とみなす
- 定員の増加や申し込みのキャンセルがあった場合は、ActiveRecord のフックで繰り上げをチェック
- 繰り上がった参加者には通知を送る（後ほど実装）

#### ■Ticket テーブルの追加
現時点ではEvent テーブルに定員カラムを追加する。
~~tebukuro の Ticket テーブルを流用？~~
~~- テーブル：~~ 
~~- `Ticket`~~
~~- カラム：~~
~~- `event_id` (number, not null) : 外部キー~~
~~- `quantity`  (number, nut null) : イベントの定員~~
~~- `cost`  (number, nut null) : イベントの参加費用（今はまだ不要かも？）~~

以下の方式はボツ。
１．~~参加者テーブルにフラグを追加~~
２．~~キャンセル待ちテーブルを新規に追加~~

**Comment by murajun1978** [comment]
定員とするかチケットとするかですね。
そこは決めときたい！
定員ならカラム追加で、チケットならテーブル追加

キャンセル待ちに関してはフラグやテーブルなど作成せずに、参加登録のTop10とかにしたい
申し込みやキャンセルが発生したら、hookで繰り上げなどをチェックして繰り上がった参加者には通知するなどの処理にしたい

**Comment by ytorii** [comment]
確かに旧tebukuro には Ticket テーブルがありました！
定員以外にも参加費用なども管理するには、その方が良さそうですね。

キャンセル待ちについては、３が該当しますね。
Issue を修正しておきます！

**Comment by ogom** [comment]
モデルはチケットごとに定員があり、整理券と入場券でキャンセル待ちの状態を保持するイメージです。
connpass 参加申し込みの枠という概念に近いイメージです。

* コミュニティは複数のイベントを持つ
* イベントに参加するには入場券が必要
* イベントには制限人数がある
* 制限人数を越えるとキャンセル待ちの整理券を配布
* 入場券をキャンセルするとキャンセル待ちが繰上げ

## example

名前付けは４パターンを出してみた。

### community

* community: コミュニティ
* community_event: コミュニティのイベント
* community_event_profile: イベントの概要
* community_event_participant: イベントの参加者
* community_event_participant_numbered_ticket: 参加者の整理券
* community_event_participant_admission_ticket: 参加者の入場券

### house

* house: コミュニティ
* house_event: コミュニティのイベント
* house_event_profile: イベントの概要
* house_event_cast: イベントの参加者（配役）
* house_event_cast_numbered_ticket: 参加者（配役）の整理券
* house_event_cast_admission_ticket: 参加者（配役）の入場券

### family

* family: コミュニティ
* family_event: コミュニティのイベント
* family_event_profile: イベントの概要
* family_event_structure: イベントの参加者（構成）
* family_event_structure_numbered_ticket: 参加者（構成）の整理券
* family_event_structure_admission_ticket: 参加者（構成）の入場券

### group

* group: コミュニティ
* group_event: コミュニティのイベント
* group_event_profile: イベントの概要
* group_event_role: イベントの参加者（役割）
* group_event_role_numbered_ticket: 参加者（役割）の整理券
* group_event_role_admission_ticket: 参加者（役割）の入場券

**Comment by ytorii** [comment]
この場合は、入場券と整理券を別々のテーブルにして保持するイメージでしょうか？
文章では自分がイメージしたものを説明しづらいので、Plant UML で ER図を作成しました。
（画像大きくてすみません。。）
![erd](https://user-images.githubusercontent.com/10824691/33985558-543b3fe0-e0fe-11e7-8959-5221bd437868.png)

**Comment by ytorii** [comment]
現状ではシンプルな方法で実装するため、以下の方針を取ります。
- 定員はEvent テーブルのカラムとする
- キャンセル待ちは参加登録者のTop10（定員10人の場合）に入っているかどうかで判定する
