### ISSUE TITLE
DNSの設定をみんなでできるようにしたい。

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#231]
DNSどこかに移動させたい。今はConoHa。
この状態だと @murajun1978 しか触れないので、AWSとかに移動してみんなで触れるようにする。

移動先は要検討。なんかここにしたら？っていうのがあれば意見だしてくださいー。

**Comment by springaki** [comment]
https://domains.google/ でやるかも。良さそう

**Comment by murajun1978** [comment]
GCPへ移行done
