### ISSUE TITLE
フロントで入力項目のバリデーションを追加する

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#233]
## Packages for validation
- https://github.com/ansman/validate.js
- https://github.com/skaterdav85/validatorjs

ほかにもあれば！

**Comment by murajun1978** [comment]
個人的には `validatorjs` かな

**Comment by ytorii** [comment]
`validatorjs` は手軽に導入できそうですし、日本語対応してくれているのが有難いですね:smile:

**Comment by ytorii** [comment]
[ tebukuro-client #46](https://github.com/shinosakarb/tebukuro-client/pull/46)の PR にて対応したため、Close します。
