### ISSUE TITLE
ユーザー管理機能の要件およびライブラリについて

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#236]
### Question contents:質問内容
ユーザー管理機能を実装するにあたって、要件を洗い出し、導入するライブラリを検討したいと考えています。
特に要件についてご意見よろしくお願いします！

### Problems and suggestions:問題・課題点/提案
ユーザー管理機能の要件
- 認証方式
  - OAuth（2.0）
    - 連携先：github、twitter、facebook
  - メールアドレス認証（今はまだ不要？）

- セッション管理方式（いづれかを選択）
  - 従来通り Cookie を利用して、サーバー側でセッションを保持
  - JWT を利用して、クライアント側でセッションを保持
 JWT でセッションを管理することには問題があるとの指摘もあります（[参考記事](http://postd.cc/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid/)）。
  - Devise Token Auth でトークンを使用、サーバー側でDBと突き合わせて検証

- 権限の認可
  -  参加キャンセルは本人のみ可能

### Countermeasure:対応方法（案）
バックエンドに導入するライブラリ候補：
- ユーザー管理（いづれかを選択）
  - [Devise](https://github.com/plataformatec/devise)
    - [Devise Token Auth](https://github.com/lynndylanhurley/devise_token_auth) （トークン でセッション管理する場合）
  - [Active Admin](https://github.com/activeadmin/activeadmin)
  - 外部サービスの利用： [Firebase](https://firebase.google.com/docs/auth/web/start?hl=ja) ( + [knock](https://github.com/nsarno/knock) gem?)

- OAuth
  - [oauth2](https://github.com/oauth-xx/oauth2)
  - [omniauth-github](https://github.com/omniauth/omniauth-github)

- 権限の認可
  - [pundit](https://github.com/elabs/pundit)

### 補足
旧tebukuro では以下の方式でした。関連Issue: #18 
ユーザー認証：
- フロントエンド： redux-auth （OAuth のアカウント連携 は別Window で許可する）
- バックエンド： devise-token-auth で redux-auth と連携してクライアントを認証

OAuth：
- omniauth-github

権限の認可：
- バックエンドで pundit gemを使用

**Comment by ytorii** [comment]
個人的にはセッション管理については、まずは従来の Cookie による管理でも良いと考えています。OAuth との連携の辺りはまだよく理解できていないませんが。。

**Comment by murajun1978** [comment]
Firebaseなど外部サービスで認証するのもありですね :smile: 

https://firebase.google.com/docs/auth/web/start?hl=ja

**Comment by ytorii** [comment]
なるほど、外部サービスを使う方法もあるんですね:bulb:
候補に追加しました！

**Comment by ytorii** [comment]
現時点ではユーザーは少人数を想定しているため、以下の要件・ライブラリとします。
- バックエンド
  - devise_token_auth でユーザーを管理、トークンを発行してセッション管理
- フロントエンド
  - [redux-token-auth](https://www.npmjs.com/package/redux-token-auth)でトークンを管理
  - もしくは独自処理でトークンを管理

**Comment by ytorii** [comment]
ユーザー認証についてのEpic ( #237 ) が作成されたので、本件 Close します！
