### ISSUE TITLE
ユーザ認証してキャンセルや後々の権限関係の機能の礎にしたい

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#237]
- ユーザ認証したい
- キャンセル機能につかう
- 今後、権限関係の機能の為にココで入れておきたい...

**Comment by ytorii** [comment]
#236 の Issue から、現時点での決定事項を転載しておきます。

現時点ではユーザーは少人数を想定しているため、以下の要件・ライブラリとする。
- バックエンド
  - devise_token_auth でユーザーを管理、トークンを発行してセッション管理
- フロントエンド
  - [redux-token-auth](https://www.npmjs.com/package/redux-token-auth)でトークンを管理
  - もしくは独自処理でトークンを管理

**Comment by ytorii** [comment]
redux-token-auth に関するメモ
- トークン等はブラウザの `localStorage` に保存（React Native の `AsyncStorage` は未対応）
- 認証のための以下の Action と Reducer を提供する
  - `reduxTokenAuthReducer`
  - `registerUser`  `signInUser`  `signOutUser`  `verifyCredentials`

**Comment by ytorii** [comment]
フロントエンドの OAuth認証について、自分なりにまとめてみました。
redux-token-auth とは別に、redux-auth より依存パッケージを減らした redux-oauth というパッケージもありました。
いずれのパッケージでも基本的にはポップアップ画面で認証→結果を元画面に連携してトークンを取得という流れのようです。

| 項目 | [redux-auth](https://github.com/lynndylanhurley/redux-auth) | [redux-oauth](https://github.com/yury-dymov/redux-oauth) | 自作 |
| :--- | :--- | :--- | :--- |
| 長所 | スター数が多く最も有名 | - redux-authより依存パッケージが少ない<br> - action〜reducerの処理までをカバー | tebukuro に合わせて好きに作れる |
| 短所 | 依存パッケージが多い上に開発が止まってる | スター数が少なく今は開発は止まってる | - テストの作成など工数が掛かる（２〜３スプリント？）<br> - 車輪の再発明かも？ |
| 開発状態 | １年半前まで | 半年前まで | 動作検証までは済み |
| 依存パッケージ数 | 11<br> (スタイル用のパッケージ含む)  | 6 <br> (immutable,<br> isomorphic-fetch<br> js-cookie, lodash,<br> query-string, redux-immutablejs) | 3 <br> ( axios,query-string,<br>devise-token-client ) 
| 認証処理の流れ | ポップアップ上で認証、トークンを取得 | 同一処理 | 同一処理 |
| トークン保存先 | LocalStorage | cookie | LocalStorage |

**Comment by ytorii** [comment]
tebukuro ではバックエンド環境があるので、上記のようなフロントエンド側でプロバイダーと通信するのではなく、バックエンド側でプロバイダーとの通信および認証を行う仕様とします。
この方式の方が、セキュリティの観点からも望ましく、CORSによる制約を受けることもありません。

**Comment by springaki** [comment]
ログイン機能は出来ている。
ログイン画面を作ったらこの epicは終了

**Comment by murajun1978** [comment]
# Frontend Todos
- [ ] create session compoennt (HOC)
- [ ] create action and reducer (for redux)
- [ ] create page header (display user info when user signed in)

**Comment by ogom** [comment]
ログイン画面ができて、イベント参加後のキャンセルが可能

**Comment by ytorii** [comment]
Done.
