### ISSUE TITLE
イベント日時を過ぎるとイベント参加登録ができないようになって欲しい

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#243]

**Comment by ytorii** [comment]
このエピックでやる作業です。他にもあれば追加お願いします:raised_hands:
下記に加えて、日付を扱うのでタイムゾーンの事も考える必要があると思ってます。

- フロントエンド
  - イベントの開始日（EventStartsAt）と終了日（EventEndsAt）を設定できるようにする
  - イベントの**開始日**が過ぎた後は「参加登録」ボタンが「受付終了しました」ボタンになる

- バックエンド
  - Event Modelで開始日（event_starts_at）と終了日（event_ends_at）のパラメータを入力必須とする。
日付の形式を正規表現でバリデーションする（複雑になりそうなら、今はまだいいかな？）
  - イベントへの参加登録時に、現在時刻が参加期限内かバリデーションする（Event model に `within_deadline?` みたいなメソッドを生やす）

**Comment by murajun1978** [comment]
> イベントの開始日が過ぎた後は「参加登録」ボタンが「受付終了しました」ボタンになる

ラベルでいいと思いますー :smile:

**Comment by ytorii** [comment]
確かにラベルの方が使いやすいですね！
コメントを修正しました:smiley:

**Comment by ytorii** [comment]
タイムゾーンの取り扱いについて、↓のような感じで考えてます。
- フロントエンド／バックエンド間の日時データのやり取り
  -  ISO8601 形式（例：2018-01-01T09:00:00Z）のUTC時刻のみ
- バックエンド
  - 日時は全て UTC で処理、保存
  - バリデーションもこの形式に従っていることを確認
- フロントエンド
  - バックエンドからはUTC時刻で日時データを受け取り、ローカルのタイムゾーン時刻（JSTなど）に変換して表示
  - 日時の入力フォームはローカル時刻で入力、[moment.js](https://momentjs.com/)などでUTC時刻に変換
  - フォーム送信時は toISOString() 関数などで、ISO8601形式に変換し送信

**Comment by ytorii** [comment]
バックエンド、フロントエンド共に必要な修正が完了しています。
後は本番環境で受け入れ確認できれば、本Epic は完了する認識です。
