### ISSUE TITLE
別のサイトに参加登録ボタン、参加者リストを埋め込めるようにしたい。

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#244]
そもそも綺麗なティザーサイトで訴求してるのに、申込み画面が Doorkeeperや connpassみたいなティザーサイトとデザイン統一されてない所に移動させられてゲンナリする(らしい...)

たとえば Stripe決済みたいにボタンを埋め込んでおいて、ポップアップで登録して、完了したら閉じる。みたいな流れだとシームレスにイベント登録サービスを提供できて嬉しい。

- 任意サイトに組み込んで
- ポップアップ表示して
- ポップアップ内で各種API をたたくようなイメージ

**Comment by ytorii** [comment]
既にあるイベント管理サービスでは、↓のような感じで利用するみたいです。
https://help.eventregist.com/hc/ja/articles/204777777-%E7%94%B3%E8%BE%BC%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0-%E5%9F%8B%E8%BE%BC%E7%94%A8%E3%83%91%E3%83%BC%E3%83%84-

**Comment by springaki** [comment]
出来てる事を確認した
