### ISSUE TITLE
tebukuro.shinosakarb.org で動作確認できるようにしてほしい

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro#245]
イベント作ろうとしたらこんなメッセージがでてきました...

![tebukuro_shinosakarb_org_event_new_.png](https://images.zenhubusercontent.com/54b9fb307c6ccc6277a6ed28/80d9d47a-bf8e-449d-b5e2-fde01206aa75)

**Comment by springaki** [comment]
UI検証を通してEPICの Accept判定をしたいので、サーバデプロイして機能確認できるようにしておいてもらえると助かります。

**Comment by ytorii** [comment]
#251 および #254 の対応で動作確認できるようになったので close します！
