### ISSUE TITLE
参加登録時の名前をユーザー情報から自動取得する

### ISSUE THREAD

**Issue by ytorii** [shinosakarb/tebukuro#255]
### Question contents:質問内容
参加登録時の参加者名は現在フォームで入力しています。
認証機能の実装に伴い、参加者名はユーザー情報から自動取得するようにしたいと思います。

### Problems and suggestions:問題・課題点/提案
認証機能が実装できユーザー情報から名前を取得できるようになったので、フォームでの入力は不要と考えています。
１ユーザーで複数人登録できるようにしておきたい！ という事であれば、現状のままで良いと思っています。

### Countermeasure:対応方法（案）
- フロントエンド
  - 参加登録フォームを削除して、参加登録／キャンセル待ち登録 ボタンのみにする
  - バックエンドに渡すパラメータは event_id のみとする
- バックエンド
  - 認証機能は実装済み
  - 参加者名を `current_user.name` から取得する

変更後の画面イメージ：
![screenshot from 2018-03-13 00-33-48](https://user-images.githubusercontent.com/10824691/37316007-101476f0-26a0-11e8-8d34-d63fe192faa0.png)

**Comment by murajun1978** [comment]
@ytorii 
> 参加者名を current_user.name から取得する 

これがイメージできなかった
どのページに表示するデータですか？

**Comment by ytorii** [comment]
参加登録時にバックエンドで、参加者は名前を `name` として保存するので、その時にバックエンド内で使用することを想定しています。
`user_id` も保存するので、`name` が必ず必要というわけではないと思いますが。。

**Comment by murajun1978** [comment]
Userとリレーションするなら、 `name` は不要だと思います

**Comment by murajun1978** [comment]
こんな感じのイメージですが

```
e.g.

@participant = Participant.new(event: @event, user: current_user)
```

**Comment by ytorii** [comment]
確かにご指摘の通り、User とリレーションするから name を直接もつのは不要ですね。
とりあえずPR作成してみますー

**Comment by ytorii** [comment]
#256 が merge されたので close しますー
