### ISSUE TITLE
APIドキュメントのDockerを作成する

### ISSUE THREAD

**Issue by ogom** [shinosakarb/tebukuro#261]
### Problems and suggestions:問題・課題点/提案

APIドキュメント はローカルで実行する前提なので Docker に移管する。

* APIドキュメントDockerは別の Dockerfile に設定する。
* API Blueprint なら node.js の 環境が必要。
* docker-compose  の build オプションでサービス名を指定できる方が確認する。
    * デプロイででキュメントが不要なら除外したい

**Comment by ytorii** [comment]
Done.
