### ISSUE TITLE
ユーザはイベントにチケットを追加できる

### ISSUE THREAD

**Issue by murajun1978** [shinosakarb/tebukuro#44]
### ストーリー
ユーザはイベントにチケットを追加できる

### チケット
* ラベル
* 価格
* チケット枚数
* 購入可能期間

|attribute|type|description|
|:---|:---|:---|
|name|varchar|チケット名|
|cost|int|価格|
|quantity|int|枚数
|sale_starts_at|datetime|購入可能な開始日時|
|sale_ends_at|datetime|購入可能な終了日時|

**Comment by murajun1978** [comment]
複数登録できるようにする。

#### endpoint
POST `/communities/:community_id/events/:event_id/tickets`

#### request params
```
{
  "tickets": [
    {
      "name": "free",
      "cost": 500,
      "quantity": 10
    }
  ]
}
```

**Comment by murajun1978** [comment]
更新

#### endpoint
PATCH `/communities/:community_id/events/:event_id/tickets/:id`

#### request params
```
{
  "name": "free",
  "cost": 500,
  "quantity": 10
}
```

#### endpoint
DELETE `/communities/:community_id/events/:event_id/tickets/:id`

**Comment by gazayas** [comment]
I'd like to try.

Will this `belong_to :user through :events` ?

There is no user now, but I can comment out that section

**Comment by murajun1978** [comment]
> Is `belongs_to :user through :events` correct?

yes, it is correct 💮

**Comment by gazayas** [comment]
Thank you!

**Comment by gazayas** [comment]
Do I need to nest the tickets inside event?
Like this:
```
def event_params
    params.require(:event).permit(:name, :description,
                                  :event_starts_at, :event_ends_at,
                                  tickets_attributes: [:name, :cost, :quantity])
end
```

or should it have its own controller?

Sorry for asking a lot of questions!

**Comment by chimame** [comment]
https://github.com/shinosakarb/tebukuro/issues/18 merged
