### ISSUE TITLE
てぶくろのイラスト

### ISSUE THREAD

**Issue by ogom** [shinosakarb/tebukuro#59]
### 提案

[いらすとや](http://www.irasutoya.com/) でイメージに合いそうな *てぶくろ* を見つけました。
トップページのイラストに使用しませんか？（素材は、個人、法人、商用、非商用問わず無料で利用できます。）

![winter_tebukuro](http://4.bp.blogspot.com/-dMHKByNfZxo/Uku9_iuHWHI/AAAAAAAAYqg/LjlcTLrN44o/s800/winter_tebukuro.png)

**Comment by chimame** [comment]
https://github.com/shinosakarb/tebukuro/issues/19 こっちと似た話題？

**Comment by ogom** [comment]
Github Page とか Readme などで使えそうです。

**Comment by murajun1978** [comment]
#64 merged 🎉
