### ISSUE TITLE
認可に関するテーブル作成

### ISSUE THREAD

**Issue by macera** [shinosakarb/tebukuro#9]
User
Owner
Admin

**Comment by murajun1978** [comment]
### 要件
* コミュニティを作成したユーザは、デフォルトでOwnerに登録する
* コミュニティのOwnerは、他のユーザをAdminに登録できる
* 重複したユーザは登録できない

**Comment by macera** [comment]
devise使いますか？

**Comment by murajun1978** [comment]
[devise](https://github.com/plataformatec/devise) + [OmniAuth](https://github.com/omniauth/omniauth)でいきましょうか

**Comment by springaki** [comment]
tebukuro reboot の為、一旦 close します。
