### ISSUE TITLE
Create event registration screen

### ISSUE THREAD

**Issue by chimame** [shinosakarb/tebukuro#92]
### Problems and suggestions:問題・課題点/提案
Event registration screen does not exist.

### Countermeasure:対応方法（案）
Create event registration screen.

The input items are as follows.
* event name(text)
* description(textarea)
* event start time(datetime-local)
* event end time(datetime-local)

event registration screen changes from event list screen or community screen.

**Comment by springaki** [comment]
tebukuro reboot の為、一旦 close します。
